#!/usr/bin/env ruby

require "set"

# command to run
cmd = ARGV[0] || "commands"

# array of done (SUCCEEDED) commands
done = (ENV["DONE"] || "").split.to_set

case cmd
when "commands"
  puts "test"
  puts "fanout-1a"
  puts "fanout-1b"
  if done.include?("fanout-1a") && done.include?("fanout-1b")
    puts "fan-in"
  end
  if done.include?("fan-in")
    puts "fail"
    puts "succeed"
  end

when "test"
  puts "im totally running tests bro"

when "fanout-1a"
  puts "this is only the beginning"

when "fanout-1b"
  puts "this too"

when "fan-in"
  puts "ok now its over"

when "fail"
  puts "i tried so hard and got so far"
  puts "and in the end"
  puts "it didnt even matter"
  exit 1

when "succeed"
  puts "we did it"
end
